export function getClientBenefitTemplate(): Record<string, string>[] {
  return [
    {
      country: "IE",
      benefitCategory: "HEALTH",
      benefitName: "Company Health Insurance",
      coverLevel: "Level 2 - Room + Semi-Private",
      isCore: "true",
      employerFunded: "true",
      isVoluntary: "false",
      isFlexible: "false",
      coversSpouse: "true",
      coversDependents: "true",
      costCurrency: "EUR",
      annualCostPerEmployee: "2500",
      employeeContributionPercent: "25",
      healthExcess: "150",
      healthCopayPercent: "",
      healthInpatientLimit: "1000000",
      healthOutpatientLimit: "15000",
      lifeCoverMultiple: "",
      lifeFixedCoverAmount: "",
      ipBenefitPercent: "",
      ipWaitingPeriodWeeks: "",
      ciCoverMultiple: "",
      ciFixedCoverAmount: "",
      dentalAnnualLimit: "",
      dentalOrthoIncluded: "",
      pensionEmployerPct: "",
      pensionEmployeePct: "",
      provider: "Laya Healthcare",
      notes: "",
    },
    {
      country: "IE",
      benefitCategory: "PENSION",
      benefitName: "Company Pension Scheme",
      coverLevel: "Defined Contribution",
      isCore: "true",
      employerFunded: "true",
      isVoluntary: "false",
      isFlexible: "false",
      coversSpouse: "false",
      coversDependents: "false",
      costCurrency: "EUR",
      annualCostPerEmployee: "5000",
      employeeContributionPercent: "5",
      healthExcess: "",
      healthCopayPercent: "",
      healthInpatientLimit: "",
      healthOutpatientLimit: "",
      lifeCoverMultiple: "",
      lifeFixedCoverAmount: "",
      ipBenefitPercent: "",
      ipWaitingPeriodWeeks: "",
      ciCoverMultiple: "",
      ciFixedCoverAmount: "",
      dentalAnnualLimit: "",
      dentalOrthoIncluded: "",
      pensionEmployerPct: "6",
      pensionEmployeePct: "5",
      provider: "Irish Life",
      notes: "Auto-enrolment scheme",
    },
  ];
}

export function getBrokerClientTemplate(): Record<string, string>[] {
  return [
    {
      companyName: "Acme Corp",
      companyEmail: "hr@acmecorp.com",
      contactName: "Jane Smith",
      industry: "J62",
      employeeCount: "250",
      employeeCountRange: "251-1000",
      country: "IE",
      benefitCategory: "HEALTH",
      benefitName: "Group Health Insurance",
      coverLevel: "Level 2",
      isCore: "true",
      employerFunded: "true",
      isVoluntary: "false",
      isFlexible: "false",
      coversSpouse: "true",
      coversDependents: "true",
      costCurrency: "EUR",
      annualCostPerEmployee: "2800",
      employeeContributionPercent: "20",
      healthExcess: "100",
      healthCopayPercent: "",
      healthInpatientLimit: "",
      healthOutpatientLimit: "",
      lifeCoverMultiple: "",
      lifeFixedCoverAmount: "",
      ipBenefitPercent: "",
      ipWaitingPeriodWeeks: "",
      ciCoverMultiple: "",
      ciFixedCoverAmount: "",
      dentalAnnualLimit: "",
      dentalOrthoIncluded: "",
      pensionEmployerPct: "",
      pensionEmployeePct: "",
      provider: "VHI",
      notes: "",
    },
    {
      companyName: "Beta Industries",
      companyEmail: "benefits@betaind.com",
      contactName: "John Doe",
      industry: "C21",
      employeeCount: "1200",
      employeeCountRange: "1001-5000",
      country: "GB",
      benefitCategory: "LIFE",
      benefitName: "Death in Service",
      coverLevel: "4x salary",
      isCore: "true",
      employerFunded: "true",
      isVoluntary: "false",
      isFlexible: "false",
      coversSpouse: "false",
      coversDependents: "false",
      costCurrency: "GBP",
      annualCostPerEmployee: "400",
      employeeContributionPercent: "",
      healthExcess: "",
      healthCopayPercent: "",
      healthInpatientLimit: "",
      healthOutpatientLimit: "",
      lifeCoverMultiple: "4",
      lifeFixedCoverAmount: "",
      ipBenefitPercent: "",
      ipWaitingPeriodWeeks: "",
      ciCoverMultiple: "",
      ciFixedCoverAmount: "",
      dentalAnnualLimit: "",
      dentalOrthoIncluded: "",
      pensionEmployerPct: "",
      pensionEmployeePct: "",
      provider: "Aviva",
      notes: "",
    },
  ];
}

export function getAdminBenefitTemplate(): Record<string, string>[] {
  return [
    {
      companyName: "Acme Corp",
      country: "IE",
      benefitCategory: "HEALTH",
      benefitName: "Company Health Insurance",
      coverLevel: "Level 2 - Room + Semi-Private",
      isCore: "true",
      employerFunded: "true",
      isVoluntary: "false",
      isFlexible: "false",
      coversSpouse: "true",
      coversDependents: "true",
      costCurrency: "EUR",
      annualCostPerEmployee: "2500",
      employeeContributionPercent: "25",
      healthExcess: "150",
      healthCopayPercent: "",
      healthInpatientLimit: "1000000",
      healthOutpatientLimit: "15000",
      lifeCoverMultiple: "",
      lifeFixedCoverAmount: "",
      ipBenefitPercent: "",
      ipWaitingPeriodWeeks: "",
      ciCoverMultiple: "",
      ciFixedCoverAmount: "",
      dentalAnnualLimit: "",
      dentalOrthoIncluded: "",
      pensionEmployerPct: "",
      pensionEmployeePct: "",
      provider: "Laya Healthcare",
      notes: "",
    },
    {
      companyName: "Beta Industries",
      country: "GB",
      benefitCategory: "LIFE",
      benefitName: "Death in Service",
      coverLevel: "4x salary",
      isCore: "true",
      employerFunded: "true",
      isVoluntary: "false",
      isFlexible: "false",
      coversSpouse: "false",
      coversDependents: "false",
      costCurrency: "GBP",
      annualCostPerEmployee: "400",
      employeeContributionPercent: "",
      healthExcess: "",
      healthCopayPercent: "",
      healthInpatientLimit: "",
      healthOutpatientLimit: "",
      lifeCoverMultiple: "4",
      lifeFixedCoverAmount: "",
      ipBenefitPercent: "",
      ipWaitingPeriodWeeks: "",
      ciCoverMultiple: "",
      ciFixedCoverAmount: "",
      dentalAnnualLimit: "",
      dentalOrthoIncluded: "",
      pensionEmployerPct: "",
      pensionEmployeePct: "",
      provider: "Aviva",
      notes: "",
    },
  ];
}

export function getAdminBrokerTemplate(): Record<string, string>[] {
  return [
    {
      email: "broker@insurancefirm.com",
      name: "Sarah O'Brien",
      companyName: "Insurance Firm Ltd",
      licenseNumber: "BRK-2024-001",
      countriesActive: "IE,GB",
    },
  ];
}

export function getAdminClientTemplate(): Record<string, string>[] {
  return [
    {
      email: "hr@newcompany.com",
      name: "Tom Murphy",
      companyName: "New Company Ltd",
      country: "IE",
      industry: "J62",
      employeeCount: "150",
      brokerEmail: "broker@insurancefirm.com",
    },
  ];
}
